import day1.script
import day2.script
import day3.script
import day4.script
import day5.script
import day6.script
import day7.script
import day8.script
import day9.script
import day10.script
import day11.script
import day12.script
import day13.script
import day14.script
import day15.script
